[ClassVersion("1.0.0"), FriendlyName("PostgreSqlInstall")]
class DSC_PostgreSqlInstall : OMI_BaseResource
{
    [Key,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] String Ensure;
    [Required,ValueMap{"9", "10", "11", "12", "13"},Values{"9", "10", "11", "12", "13"}] String Version;
    [Required, Description("Specifies the path of the installer.")] String InstallerPath;
    [Write, Description("Specifies the name of the Postgres service.")] String ServiceName;
    [Write, Description("Specifies the install directory for the install.")] String InstallDirectory;
    [Write, Description("Specifies the port of the service.")] UInt16 ServerPort;
    [Write, Description("Specifies the data directory.")] String DataDirectory;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("Specifies the account used to run the service.")] String ServiceAccount;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("Specifies the super admin for the install.")] String SuperAccount;
    [Write, Description("Specifies the components to be installed.")] String Features[];
    [Write, Description("Specifies the option file used for the install.")] String OptionFile;
};
